export type {
  Movie,
  Actor,
  CastMember,
  Rating,
  CreateMovieDto,
  UpdateMovieDto,
  CreateActorDto,
  UpdateActorDto,
  CreateRatingDto,
  UpdateRatingDto,
  CreateCastMemberDto,
  LoginDto,
  MovieGenre,
  PaginationOptions,
  PaginatedResponse,
  SearchParams,
  ApiError,
  ValidationError,
} from "./types";

export {
  MovieGenreSchema,
  CastMemberSchema,
  RatingSchema,
  ActorSchema,
  MovieSchema,
  CreateMovieDtoSchema,
  UpdateMovieDtoSchema,
  CreateActorDtoSchema,
  UpdateActorDtoSchema,
  CreateRatingDtoSchema,
  UpdateRatingDtoSchema,
  CreateCastMemberDtoSchema,
  LoginDtoSchema,
  ApiErrorSchema,
  ValidationErrorSchema,
} from "./schemas";
