services:
  db:
    image: postgres:16
    restart: always
    ports:
      - "5438:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=moviedb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/moviedb?schema=public
      - JWT_SECRET=demo-jwt-secret-not-for-production
      - API_SECRET=movie-api-secret-2024
      - NODE_ENV=development
      - PORT=4000
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
